services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Make\:
    resource: '../Classes/*'

  B13\Make\PackageResolver:
    public: true

  B13\Make\Command\Component\BackendControllerCommand:
    tags:
      - name: 'console.command'
        command: 'make:backendcontroller'
        description: 'Create a backend controller'
        schedulable: false

  B13\Make\Command\Component\CommandCommand:
    tags:
      - name: 'console.command'
        command: 'make:command'
        description: 'Create a console command'
        schedulable: false

  B13\Make\Command\Component\EventListenerCommand:
    tags:
      - name: 'console.command'
        command: 'make:eventlistener'
        description: 'Create a PSR-14 event listener'
        schedulable: false

  B13\Make\Command\ExtensionCommand:
    tags:
      - name: 'console.command'
        command: 'make:extension'
        description: 'Create a TYPO3 extension'
        schedulable: false

  B13\Make\Command\Component\MiddlewareCommand:
    tags:
      - name: 'console.command'
        command: 'make:middleware'
        description: 'Create a PSR-15 middleware'
        schedulable: false

  B13\Make\Command\RunTestsCommand:
    tags:
      - name: 'console.command'
        command: 'make:runtests'
        description: 'Setup runTests.sh and docker-compose.yml in the ./Build folder to run tests, linter, cgl in a Docker environment'
        schedulable: false